/-
Copyright (c) 2026 Lasse Rempe. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Lasse Rempe
-/

import Mathlib

/-!
# The exponential map is chaotic

This file states a collection of benchmark consequences of Misiurewicz's theorem for the
complex exponential map. The proofs are supplied in `Solution.lean`.

The goal is a formalisation of the main results in the paper
"The Exponential Map is Chaotic: An Invitation to Transcendental Dynamics"
by Zhaiming Shen and Lasse Rempe-Gillen.

The formalisation was carried out with the help of generative AI, including
Microsoft 365 Copilot, Claude and, particularly, ChatGPT (GPT-5.6 Sol and GPT-6 Astra).
Preparation for submission to GitHub and Palomar was also assisted by ChatGPT.

This challenge file has been checked for correctness and for correspondence with the theorems
in the aforementioned paper.

The principal sources for the formalisation—which was mostly carried out autonomously by AI
tools, with guidance from the author—were the paper above and, for the density of the escaping
set, an existing formalisation of Misiurewicz's original proof in HOL Light. The latter was
written by John Harrison in 2014 in response to a challenge posed by the author on the FOM
(Foundations of Mathematics) mailing list and communicated to Harrison by Freek Wiedijk.

Links:
* [The original challenge](https://fomarchive.ugent.be/2014-October/018293.html)
* [The announcement of Harrison's formalisation](https://fomarchive.ugent.be/2014-November/018390.html)

Auxiliary results not formalised as benchmark statements in this file:

* Lemma 3.1, the Schwarz lemma, is already present in Mathlib.
* Theorem 3.3 (Pick's theorem), Proposition 3.4 (examples of hyperbolic metrics) and Lemma 4.2
  belong to the paper's hyperbolic-metric proof route, which is not followed here.
* Proposition 5.3 gives contracting inverse branches along arbitrary escaping orbits.
* Observation 5.4 gives two-step covering by discs of radius `2 * π` with arbitrary centres
  sufficiently far to the right. Our development has a related covering estimate for discs
  of radius `8` centred on the real axis.
* Lemma 6.2 is the paper's precise inverse-branch statement for `f²`. Our development has
  related closing inverse branches sufficient to prove density of periodic points.

We use existing Mathlib definitions and notation where possible. The relevant notion of a
normal family is not currently defined in Mathlib, so we give a general definition—not
restricted to holomorphic functions—using Mathlib's existing framework for locally uniform
convergence.
-/

open Function Filter Set Metric

namespace ExpChaotic

noncomputable section

/-- The `n`-th iterate of the complex exponential map. -/
abbrev expIterate (n : ℕ) : ℂ → ℂ := Complex.exp^[n]

/-- A point escapes if its orbit eventually leaves every centred Euclidean ball. -/
def EscapesToInfinity (z : ℂ) : Prop :=
  ∀ R : ℝ, ∃ N : ℕ, ∀ n : ℕ, (n ≥ N → R ≤ ‖expIterate n z‖)

/-- The escaping set of the complex exponential map. -/
def escapingSet : Set ℂ := {z | EscapesToInfinity z}

/-- The set of points with dense forward orbit. -/
def denseOrbitSet : Set ℂ :=
  {z | Dense (MulAction.orbit (IterateMulAct Complex.exp) z)}

/-- The repelling periodic points of the complex exponential map. -/
def repellingPeriodicSet : Set ℂ :=
  {p | ∃ n : ℕ, 0 < n ∧ IsPeriodicPt Complex.exp n p ∧
    1 < ‖deriv (expIterate n) p‖}

/-- The Riemann sphere as the one-point compactification of the complex plane. -/
abbrev RiemannSphere := OnePoint ℂ

/-- The canonical uniform structure on the compact Hausdorff Riemann sphere. -/
instance riemannSphereUniformSpace : UniformSpace RiemannSphere :=
  uniformSpaceOfCompactR1

/-- A sequence of maps is normal on `U` if every subsequence has a further subsequence
converging locally uniformly on `U` to some function from `U` to the uniform codomain. -/
def IsNormalSequenceOn {α β : Type*} [TopologicalSpace α] [UniformSpace β]
    (F : ℕ → α → β) (U : Set α) : Prop :=
  ∀ φ : ℕ → ℕ, StrictMono φ →
    ∃ ψ : ℕ → ℕ, StrictMono ψ ∧ ∃ g : U → β,
      TendstoLocallyUniformly (fun n (z : U) => F (φ (ψ n)) z) g atTop

/-- The Fatou set defined by local normality of the sphere-valued iterates. -/
def fatouSet (f : ℂ → ℂ) : Set ℂ :=
  {z | ∃ U : Set ℂ, IsOpen U ∧ z ∈ U ∧
    IsNormalSequenceOn (fun n z => ((f^[n]) z : RiemannSphere)) U}

/-- The Julia set, defined as the complement of the Fatou set. -/
def juliaSet (f : ℂ → ℂ) : Set ℂ := (fatouSet f)ᶜ

/-- Continuity, dense periodic points, and Mathlib's topological transitivity
for the monoid action generated by iteration. -/
def IsDevaneyChaotic (f : ℂ → ℂ) : Prop :=
  Continuous f ∧ Dense (Function.periodicPts f) ∧
    MulAction.IsTopologicallyTransitive (IterateMulAct f) ℂ

/-- The plane-valued exponential iterates, included into the Riemann sphere. -/
def sphericalExpIterate (n : ℕ) (z : ℂ) : RiemannSphere :=
  (expIterate n z : OnePoint ℂ)

/-- Corollary 5.5. Given a prescribed compact set K that omits zero,
every sufficiently high iterate of a nonempty open set covers K. -/
theorem eventually_covers_compact
    {U K : Set ℂ} (hU : IsOpen U) (hUne : U.Nonempty)
    (hK : IsCompact K) (hK0 : (0 : ℂ) ∉ K) :
    ∃ N : ℕ, ∀ n : ℕ, (n ≥ N → K ⊆ expIterate n '' U) := by
  sorry

/-- The full iterated preimage of every nonzero point is dense. -/
theorem dense_iteratedPreimages_nonzero {w : ℂ} (hw : w ≠ 0) :
    Dense {z : ℂ | ∃ n : ℕ, expIterate n z = w} := by
  sorry

/-- The full iterated preimage of the real axis is dense. -/
theorem dense_iteratedPreimages_realAxis :
    Dense {z : ℂ | ∃ n : ℕ, (expIterate n z).im = 0} := by
  sorry

/-- Theorem 1.1, part 1., and Theorem 4.1: Escaping points are dense. -/
theorem dense_escapingSet : Dense escapingSet := by
  sorry

/-- Theorem 1.1, part 2.: Points with dense forward orbit are dense. -/
theorem dense_denseOrbitSet : Dense denseOrbitSet := by
  sorry

/-- Corollary 5.6. There are uncountably many points with dense forward orbit. -/
theorem not_countable_denseOrbitSet : ¬ denseOrbitSet.Countable := by
  sorry

/-- Theorem 1.1, part 3., and Theorem 6.1: (Repelling) periodic points are dense. -/
theorem dense_repellingPeriodicSet : Dense repellingPeriodicSet := by
  sorry

/-- Theorem 5.1. The action generated by iterating the exponential map is
topologically transitive. -/
theorem topologically_transitive :
    MulAction.IsTopologicallyTransitive (IterateMulAct Complex.exp) ℂ := by
  sorry

/-- Theorem 1.2. The exponential map is chaotic in Devaney's sense. -/
theorem devaney_chaotic : IsDevaneyChaotic Complex.exp := by
  sorry

/-- Corollary 4.4 (reformulated): The sphere-valued iterates are not equicontinuous
at any point of the plane. -/
theorem not_equicontinuousAt_sphericalExpIterate (z : ℂ) :
    ¬ EquicontinuousAt sphericalExpIterate z := by
  sorry

/-- Theorem 4.3: infinitely many iterated images of a nonempty open set meet the
negative real axis. Strict negativity strengthens the nonpositive-axis statement in the paper. -/
theorem infinitely_often_hits_negative_realAxis {U : Set ℂ}
    (hU : IsOpen U) (hUne : U.Nonempty) :
    {n : ℕ | ∃ z ∈ U, (expIterate n z).im = 0 ∧ (expIterate n z).re < 0}.Infinite := by
  sorry

/-- Corollary 4.4, in the precise form of Definition 2.3. The arbitrary positive constants
give Exercise 8.7 as well; the conclusion even holds at every sufficiently late time. -/
theorem spherical_sensitive_dependence_paper {U : Set ℂ}
    (hU : IsOpen U) (hUne : U.Nonempty) {R δ : ℝ} (hR : 0 < R) (hδ : 0 < δ) :
    ∃ N : ℕ, ∀ n : ℕ, (n ≥ N → ∃ z ∈ U, ∃ w ∈ U,
      ‖expIterate n z‖ ≤ R ∧ δ ≤ ‖expIterate n z - expIterate n w‖) := by
  sorry

/-- Observation 5.2: along any escaping orbit, the real parts and the norms of the
derivatives of the iterates both tend to positive infinity. -/
theorem expansion_along_escaping_orbits {z : ℂ} (hz : EscapesToInfinity z) :
    Tendsto (fun n => (expIterate n z).re) atTop atTop ∧
      Tendsto (fun n => ‖deriv (expIterate n) z‖) atTop atTop := by
  sorry

/-- No increasing subsequence of the iterates has a locally uniform spherical limit
on a nonempty open set. The arbitrary sphere-valued limit is defined only on that set. -/
theorem not_tendstoLocallyUniformly_sphericalExpIterate
    {U : Set ℂ} (hU : IsOpen U) (hUne : U.Nonempty)
    {φ : ℕ → ℕ} (hφ : StrictMono φ) (g : U → RiemannSphere) :
    ¬ TendstoLocallyUniformly (fun n (z : U) => sphericalExpIterate (φ n) z) g atTop := by
  sorry

/-- Misiurewicz's theorem: the Julia set is the whole complex plane. -/
theorem juliaSet_exp : juliaSet Complex.exp = Set.univ := by
  sorry

end

end ExpChaotic
